.TH "src/cancellation.c" 3 "Fri Apr 24 2020" "CBMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/cancellation.c \- A function to cancel existing booking\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include '\&.\&./include/cancellation\&.h'\fP
.br
\fC#include '\&.\&./include/refund_calculation\&.h'\fP
.br
\fC#include '\&.\&./include/display_booking_details\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcancellation\fP ()"
.br
.RI "A function to cancel existing booking\&. "
.in -1c
.SH "Detailed Description"
.PP 
A function to cancel existing booking\&. 


.PP
\fBAuthor\fP
.RS 4
Spandana Manjappa Karehanumannara - kmspandanakarehanuma@cmail.carleton.ca 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void cancellation ()"

.PP
A function to cancel existing booking\&. Function helps in cancelling the tickets that are already booked Getting the booking id to cancel the ticket\&.
.PP
Displaying the booking details of the customer\&.
.PP
Confirming to proceed with the cancellation\&.
.PP
Calculating the refund amount\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CBMS from the source code\&.
