.TH "src/package_availability.c" 3 "Fri Apr 24 2020" "CBMS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/package_availability.c \- A Function to check the availability of seats in the particular cruise opted by the customer\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include '\&.\&./include/package_availability\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBpackage_availability\fP (int cruise_selected, int no_of_pass, int total_seats[])"
.br
.RI "Checks the availability of seats in the cruise\&. "
.in -1c
.SH "Detailed Description"
.PP 
A Function to check the availability of seats in the particular cruise opted by the customer\&. 


.PP
\fBAuthor\fP
.RS 4
Spandana Manjappa Karehanumannara - kmspandanakarehanuma@cmail.carleton.ca 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int package_availability (int cruise_selected, int no_of_pass, int total_seats[])"

.PP
Checks the availability of seats in the cruise\&. 
.PP
\fBParameters\fP
.RS 4
\fIcruise_selected\fP The type of cruise selected for booking\&. 
.br
\fIno_of_pass\fP Total number of passengers travelling in one booking\&. 
.br
\fIarray\fP of total seats Array of total number of seats available in all the cruise types\&.
.RE
.PP
Function takes the selected cruise type, number of passengers and total numbers of seats in all the cruise as input, and checks the seat availability for number of passengers provided in the particular selected cruise type\&.
.PP
\fBReturns\fP
.RS 4
If seats available returns -1, if seats are not available returns the count of remaining available seats in the cruise\&. 
.RE
.PP
Returns -2 if invalid parameters are provided to the function\&.
.PP
Returns -1 if seats are available in the selected cruise\&.
.PP
returns the count of remaining number of seats available in the selected cruise\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CBMS from the source code\&.
